name: Release and Deploy
on:
  push:
    tags:
      - "v*"
jobs:

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn package -D env=prod -Dmaven.test.skip=true
      - name: Upload war for deployment
        uses: actions/upload-artifact@v1
        with:
          name: warPack
          path: target/Ehr-0.3.17.war


  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download WAR
        uses: actions/download-artifact@v2
        with:
          name: warPack
      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: false
          application_name: backendAz
          environment_name: Backendaz-env
          version_label: ${{github.SHA}}
          region: us-east-1
          deployment_package: Ehr-0.3.17.war

  release:
    needs: deploy
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.PAT }}"
          prerelease: false
#  publish-Docker:
#    needs: release
#    name: Publish To Docker
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Publish to Registry
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: softechdocker/ehr-api
#          username: ${{ secrets.DOCKER_HUB_USER }}
#          password: ${{ secrets.DOCKER_HUB_PASS }}
#          tags: "latest,${{ env.RELEASE_VERSION }}"

