name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.PAT }}"
          prerelease: false
  publish-Docker:
    needs: release
    name: Publish To Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: softechdocker/ehr-api
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
          tags: "latest,${{ env.RELEASE_VERSION }}"

