# Name of the workflow
name: Release
# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"
# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.PAT }}"
          prerelease: false
  publish-Docker:
    needs: release
    name: Publish To Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download jar for Docker Job
        uses: actions/download-artifact@v1
        with:
            name: jarpack # The jar package will be checkout: jarpack/...jar
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: softechdocker/ehr-api
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
          tags: "latest,${{ env.RELEASE_VERSION }}"

